Implementations of
sphaso/noether pull request #10
Opened 2019-06-03 14:19 UTC by cottinisimone

- flatten
- flat_map
- map_error

2019-06-03 17:55 UTC, sphaso commented
https://github.com/sphaso/noether/issues/8

2019-06-03 18:01 UTC, sphaso commented
:+1: LGTM. I would wait for https://github.com/sphaso/noether/pull/9 to be merged, then rebase this branch, merge, and we're ready to publish :tada:

2019-06-03 18:22 UTC, sphaso commented
@cottinisimone oh wait, I've just realized... `flatten` is actually [join](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad.html#v:join) for `Either`.      
I'm ok with having `flat_map` and `map_error` since they don't really have an equivalent name in Haskell. What do you think?

2019-06-04 09:37 UTC, cottinisimone commented on lib/noether/either.ex
> +    ** (FunctionClauseError) no function clause matching in Noether.Either.flat_map/2
This error could be specialized like the Enum protocol (Enumerable protocol not implemented for ..)

2019-06-04 09:37 UTC, cottinisimone commented on lib/noether/either.ex
> +    ** (FunctionClauseError) no function clause matching in Noether.Either.flatten/1
Same here

2019-06-04 15:14 UTC, cottinisimone commented
I'm fine with renaming `flatten` to `join`. Anyway i'm not so sure anymore about the `flat_map` method while it is just a `bind` specialization method. Probably it is useless

2019-06-04 15:58 UTC, sphaso commented
We can add it and remove it later if we realize it's really a duplicate: _melius abundare quam deficere_

2019-06-05 17:21 UTC, sphaso approved these changes

2019-06-05 17:32 UTC, neslinesli93 requested changes
Nice work with the `is_function` guard! I'd like to see a couple typos fixed before going to master

2019-06-05 17:32 UTC, neslinesli93 commented on lib/noether/either.ex
> +  Given an `{:ok, {:ok, value}}` it flat the ok unwrapping the `value` and returning `{:ok, value}`.
I think the example has a typo: `it flattens the ok unwrapping...` rather than `it flat the ok unwrapping`

2019-06-05 17:32 UTC, neslinesli93 commented on lib/noether/either.ex
> +  Given an `{:ok, {:ok, value}}` it flat the ok unwrapping the `value` and returning `{:ok, value}`.
Same as above

2019-06-05 17:32 UTC, neslinesli93 commented on lib/noether/either.ex
> +  Given an Either and one function, it applies the function to `{:error, _}` tuple.
I think it sounds better with `the {:error, _} tuple`

2019-06-06 07:19 UTC, sphaso commented
@cottinisimone could you please rebase from master as well before the next commit on this branch? :angel:

2019-06-06 09:40 UTC, neslinesli93 approved these changes

2019-06-06 09:40 UTC, merged